name: publish

on:
  push:
    branches: [ "master" ]
    paths:
      - 'CMAWS.psd1'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'CMAWS.psd1'

  workflow_dispatch:

jobs:
  deploy:
    environment: publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set PSGallery to trusted
        shell: pwsh
        run: Set-PSReposity -Name PSGallery -InstallationPolicy Trusted -Force
      - name: Install FXPSYaml Module
        shell: pwsh
        run: Install-Module FXPSYaml -Force
      - name: Import Module
        shell: pwsh
        run: Import-Module .\CMAWS.psd1
      - name: publish module
        shell: pwsh
        run: Publish-Module -Path . -NuGetApiKey ${{ secrets.API_KEY }} -Force