name: publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    environment: publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update PowerShell Get
        run: powershell -c "Update-Module PowerShellGet -Force"
      - name: Import Module
        run: powershell -c "Import-Module ."
      - name: publish module
        run: powershell -c "Publish-Module -Path . -NuGetApiKey ${{ secrets.API_KEY }} -Force"